
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zoharLep
 */
public class clientGUI extends javax.swing.JFrame {

    // default values
    int portNumber;
    String serverAddress;
    String userName;
    Client client;
    boolean isConnect;
    
    /**
     * Creates new form client
     */
    public clientGUI() {
        initComponents();
        // default values
	portNumber = 55000;
	serverAddress = "localhost";
	userName = "Anonymous";
        client = null;
        isConnect = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connButt = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        adderssLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        showOnlineButt = new javax.swing.JButton();
        clearButt = new javax.swing.JButton();
        sendMessageField = new javax.swing.JTextField();
        sendMessageButt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BigTextArea = new javax.swing.JTextArea();
        toLabel = new javax.swing.JLabel();
        toField = new javax.swing.JTextField();
        getFileButton = new javax.swing.JButton();
        fileNameToSend = new javax.swing.JTextField();
        fileNamejLabel = new javax.swing.JLabel();
        ProceedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        connButt.setText("Connect");
        connButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connButtActionPerformed(evt);
            }
        });

        nameLabel.setText("  name:");

        userNameField.setText("user");

        adderssLabel.setText("  address: ");

        addressField.setText("localhost");

        showOnlineButt.setText("show online");
        showOnlineButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOnlineButtActionPerformed(evt);
            }
        });

        clearButt.setText("Clear");
        clearButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtActionPerformed(evt);
            }
        });

        sendMessageButt.setText("Send");
        sendMessageButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageButtActionPerformed(evt);
            }
        });

        BigTextArea.setColumns(20);
        BigTextArea.setRows(5);
        jScrollPane1.setViewportView(BigTextArea);

        toLabel.setText("  to:  ");

        getFileButton.setText("Send file");
        getFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getFileButtonActionPerformed(evt);
            }
        });

        fileNameToSend.setText("test.txt");
        fileNameToSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameToSendActionPerformed(evt);
            }
        });

        fileNamejLabel.setText("Tape the name of the file you want to download:");

        ProceedButton.setText("Proceed");
        ProceedButton.setEnabled(false);
        ProceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connButt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adderssLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showOnlineButt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileNamejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fileNameToSend, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getFileButton))
                            .addComponent(sendMessageField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendMessageButt))
                            .addComponent(ProceedButton))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connButt)
                    .addComponent(nameLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adderssLabel)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showOnlineButt)
                    .addComponent(clearButt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendMessageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendMessageButt)
                    .addComponent(toLabel)
                    .addComponent(toField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameToSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getFileButton)
                    .addComponent(fileNamejLabel)
                    .addComponent(ProceedButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connButtActionPerformed
        // default values
        if (!isConnect) {
            if (addressField.getText().equals("") || userNameField.getText().equals("")) {
            BigTextArea.append("\nuser name or address is invalid\n");
            
            }
            else {
                serverAddress = addressField.getText();
                userName = userNameField.getText();
                // create the Client object
                client = new Client(serverAddress, portNumber, userName);
                // test if we can start the connection to the Server
                // if it failed nothing we can do
                if(!client.start()) return;
                isConnect = true;
            }
        }
        else {
            BigTextArea.append("\nyou are already connected\n");
        }
    }//GEN-LAST:event_connButtActionPerformed

    private void showOnlineButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOnlineButtActionPerformed
        if (isConnect) {
            client.sendMessage(new ChatMessage(ChatMessage.WHOISIN, ""));
        }
        else {
            BigTextArea.append("\nyou are not connect\n");
        }
    }//GEN-LAST:event_showOnlineButtActionPerformed

    private void clearButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtActionPerformed
        BigTextArea.setText("");
    }//GEN-LAST:event_clearButtActionPerformed

    private void sendMessageButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageButtActionPerformed
        if (!isConnect) {
            BigTextArea.append("\nyou are not connect\n");
            return;
        }
        String msg = sendMessageField.getText();
        if(msg.equalsIgnoreCase("LOGOUT")) {
            client.sendMessage(new ChatMessage(ChatMessage.LOGOUT, ""));
            isConnect = false;
        }
        // message WhoIsIn
        else {
            String toMess = toField.getText();
            if (toMess.equals("")) {
                // default to ordinary message
                client.sendMessage(new ChatMessage(ChatMessage.MESSAGE, msg));
            }
            else {
                client.sendMessage(new ChatMessage(ChatMessage.TO, msg,toMess));
            }
            
        }
    }//GEN-LAST:event_sendMessageButtActionPerformed

    private void getFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getFileButtonActionPerformed
        if (isConnect) {
            if (fileNameToSend.getText().equals("")) {
                BigTextArea.append("\nFile name is empty!\n");
                return;
            }
            client.sendMessage(new ChatMessage(ChatMessage.SENDFILE, "I want to download the file: " + fileNameToSend.getText(), this.userName, fileNameToSend.getText()));
            getFileButton.setEnabled(false);
        }
        else {
            BigTextArea.append("\nyou are not connect\n");
        }
    }//GEN-LAST:event_getFileButtonActionPerformed

    private void ProceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedButtonActionPerformed
        client.sendMessage(new ChatMessage(ChatMessage.PROCEED, ""));
        ProceedButton.setEnabled(false);
    }//GEN-LAST:event_ProceedButtonActionPerformed

    private void fileNameToSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameToSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameToSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea BigTextArea;
    public static javax.swing.JButton ProceedButton;
    private javax.swing.JLabel adderssLabel;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton clearButt;
    private javax.swing.JButton connButt;
    public static javax.swing.JTextField fileNameToSend;
    private javax.swing.JLabel fileNamejLabel;
    public static javax.swing.JButton getFileButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton sendMessageButt;
    private javax.swing.JTextField sendMessageField;
    private javax.swing.JButton showOnlineButt;
    private javax.swing.JTextField toField;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
